import { Match } from "./types";

// All 104 matches from FIFA official schedule
// Times are in UTC (confirmed by cross-referencing FIFA and ESPN)
export const matches: Match[] = [
  // ==================== Group Stage - Matchday 1 ====================
  // Results updated 2026-06-22 from ESPN
  {
    id: 1,
    stage: "group",
    dateUTC: "2026-06-11T19:00:00Z",
    team1: { name: "墨西哥", code: "MEX" },
    team2: { name: "南非", code: "RSA" },
    group: "A",
    venue: "墨西哥城",
    score1: 2,
    score2: 0,
    status: "finished",
  },
  {
    id: 2,
    stage: "group",
    dateUTC: "2026-06-12T02:00:00Z",
    team1: { name: "韩国", code: "KOR" },
    team2: { name: "捷克", code: "CZE" },
    group: "A",
    venue: "瓜达拉哈拉",
    score1: 2,
    score2: 1,
    status: "finished",
  },
  {
    id: 3,
    stage: "group",
    dateUTC: "2026-06-12T19:00:00Z",
    team1: { name: "加拿大", code: "CAN" },
    team2: { name: "波黑", code: "BIH" },
    group: "B",
    venue: "多伦多",
    score1: 1,
    score2: 1,
    status: "finished",
  },
  {
    id: 4,
    stage: "group",
    dateUTC: "2026-06-13T01:00:00Z",
    team1: { name: "美国", code: "USA" },
    team2: { name: "巴拉圭", code: "PAR" },
    group: "D",
    venue: "洛杉矶",
    score1: 4,
    score2: 1,
    status: "finished",
  },
  {
    id: 5,
    stage: "group",
    dateUTC: "2026-06-13T19:00:00Z",
    team1: { name: "卡塔尔", code: "QAT" },
    team2: { name: "瑞士", code: "SUI" },
    group: "B",
    venue: "旧金山",
    score1: 1,
    score2: 1,
    status: "finished",
  },
  {
    id: 6,
    stage: "group",
    dateUTC: "2026-06-13T22:00:00Z",
    team1: { name: "巴西", code: "BRA" },
    team2: { name: "摩洛哥", code: "MAR" },
    group: "C",
    venue: "纽约/新泽西",
    score1: 1,
    score2: 1,
    status: "finished",
  },
  {
    id: 7,
    stage: "group",
    dateUTC: "2026-06-14T01:00:00Z",
    team1: { name: "海地", code: "HAI" },
    team2: { name: "苏格兰", code: "SCO" },
    group: "C",
    venue: "波士顿",
    score1: 0,
    score2: 1,
    status: "finished",
  },
  {
    id: 8,
    stage: "group",
    dateUTC: "2026-06-14T04:00:00Z",
    team1: { name: "澳大利亚", code: "AUS" },
    team2: { name: "土耳其", code: "TUR" },
    group: "D",
    venue: "温哥华",
    score1: 2,
    score2: 0,
    status: "finished",
  },
  {
    id: 9,
    stage: "group",
    dateUTC: "2026-06-14T17:00:00Z",
    team1: { name: "德国", code: "GER" },
    team2: { name: "库拉索", code: "CUW" },
    group: "E",
    venue: "休斯顿",
    score1: 7,
    score2: 1,
    status: "finished",
  },
  {
    id: 10,
    stage: "group",
    dateUTC: "2026-06-14T20:00:00Z",
    team1: { name: "荷兰", code: "NED" },
    team2: { name: "日本", code: "JPN" },
    group: "F",
    venue: "达拉斯",
    score1: 2,
    score2: 2,
    status: "finished",
  },
  {
    id: 11,
    stage: "group",
    dateUTC: "2026-06-14T23:00:00Z",
    team1: { name: "科特迪瓦", code: "CIV" },
    team2: { name: "厄瓜多尔", code: "ECU" },
    group: "E",
    venue: "费城",
    score1: 1,
    score2: 0,
    status: "finished",
  },
  {
    id: 12,
    stage: "group",
    dateUTC: "2026-06-15T02:00:00Z",
    team1: { name: "瑞典", code: "SWE" },
    team2: { name: "突尼斯", code: "TUN" },
    group: "F",
    venue: "蒙特雷",
    score1: 5,
    score2: 1,
    status: "finished",
  },
  {
    id: 13,
    stage: "group",
    dateUTC: "2026-06-15T16:00:00Z",
    team1: { name: "西班牙", code: "ESP" },
    team2: { name: "佛得角", code: "CPV" },
    group: "H",
    venue: "亚特兰大",
    score1: 0,
    score2: 0,
    status: "finished",
  },
  {
    id: 14,
    stage: "group",
    dateUTC: "2026-06-15T19:00:00Z",
    team1: { name: "比利时", code: "BEL" },
    team2: { name: "埃及", code: "EGY" },
    group: "G",
    venue: "西雅图",
    score1: 1,
    score2: 1,
    status: "finished",
  },
  {
    id: 15,
    stage: "group",
    dateUTC: "2026-06-15T22:00:00Z",
    team1: { name: "沙特阿拉伯", code: "KSA" },
    team2: { name: "乌拉圭", code: "URU" },
    group: "H",
    venue: "迈阿密",
    score1: 1,
    score2: 1,
    status: "finished",
  },
  {
    id: 16,
    stage: "group",
    dateUTC: "2026-06-16T01:00:00Z",
    team1: { name: "伊朗", code: "IRN" },
    team2: { name: "新西兰", code: "NZL" },
    group: "G",
    venue: "洛杉矶",
    score1: 2,
    score2: 2,
    status: "finished",
  },
  {
    id: 17,
    stage: "group",
    dateUTC: "2026-06-16T19:00:00Z",
    team1: { name: "法国", code: "FRA" },
    team2: { name: "塞内加尔", code: "SEN" },
    group: "I",
    venue: "纽约/新泽西",
    score1: 3,
    score2: 1,
    status: "finished",
  },
  {
    id: 18,
    stage: "group",
    dateUTC: "2026-06-16T22:00:00Z",
    team1: { name: "伊拉克", code: "IRQ" },
    team2: { name: "挪威", code: "NOR" },
    group: "I",
    venue: "波士顿",
    score1: 1,
    score2: 4,
    status: "finished",
  },
  {
    id: 19,
    stage: "group",
    dateUTC: "2026-06-17T01:00:00Z",
    team1: { name: "阿根廷", code: "ARG" },
    team2: { name: "阿尔及利亚", code: "ALG" },
    group: "J",
    venue: "堪萨斯城",
    score1: 3,
    score2: 0,
    status: "finished",
  },
  {
    id: 20,
    stage: "group",
    dateUTC: "2026-06-17T04:00:00Z",
    team1: { name: "奥地利", code: "AUT" },
    team2: { name: "约旦", code: "JOR" },
    group: "J",
    venue: "旧金山",
    score1: 3,
    score2: 1,
    status: "finished",
  },
  {
    id: 21,
    stage: "group",
    dateUTC: "2026-06-17T17:00:00Z",
    team1: { name: "葡萄牙", code: "POR" },
    team2: { name: "刚果(金)", code: "COD" },
    group: "K",
    venue: "休斯顿",
    score1: 1,
    score2: 1,
    status: "finished",
  },
  {
    id: 22,
    stage: "group",
    dateUTC: "2026-06-17T20:00:00Z",
    team1: { name: "英格兰", code: "ENG" },
    team2: { name: "克罗地亚", code: "CRO" },
    group: "L",
    venue: "达拉斯",
    score1: 4,
    score2: 2,
    status: "finished",
  },
  {
    id: 23,
    stage: "group",
    dateUTC: "2026-06-17T23:00:00Z",
    team1: { name: "加纳", code: "GHA" },
    team2: { name: "巴拿马", code: "PAN" },
    group: "L",
    venue: "多伦多",
    score1: 1,
    score2: 0,
    status: "finished",
  },

  // ==================== Group Stage - Matchday 2 ====================
  // Results updated 2026-06-22 from ESPN
  {
    id: 24,
    stage: "group",
    dateUTC: "2026-06-18T02:00:00Z",
    team1: { name: "乌兹别克斯坦", code: "UZB" },
    team2: { name: "哥伦比亚", code: "COL" },
    group: "K",
    venue: "墨西哥城",
    score1: 1,
    score2: 3,
    status: "finished",
  },
  {
    id: 25,
    stage: "group",
    dateUTC: "2026-06-18T16:00:00Z",
    team1: { name: "捷克", code: "CZE" },
    team2: { name: "南非", code: "RSA" },
    group: "A",
    venue: "亚特兰大",
    score1: 1,
    score2: 1,
    status: "finished",
  },
  {
    id: 26,
    stage: "group",
    dateUTC: "2026-06-18T19:00:00Z",
    team1: { name: "瑞士", code: "SUI" },
    team2: { name: "波黑", code: "BIH" },
    group: "B",
    venue: "洛杉矶",
    score1: 4,
    score2: 1,
    status: "finished",
  },
  {
    id: 27,
    stage: "group",
    dateUTC: "2026-06-18T22:00:00Z",
    team1: { name: "加拿大", code: "CAN" },
    team2: { name: "卡塔尔", code: "QAT" },
    group: "B",
    venue: "温哥华",
    score1: 6,
    score2: 0,
    status: "finished",
  },
  {
    id: 28,
    stage: "group",
    dateUTC: "2026-06-19T01:00:00Z",
    team1: { name: "墨西哥", code: "MEX" },
    team2: { name: "韩国", code: "KOR" },
    group: "A",
    venue: "瓜达拉哈拉",
    score1: 1,
    score2: 0,
    status: "finished",
  },
  {
    id: 29,
    stage: "group",
    dateUTC: "2026-06-19T19:00:00Z",
    team1: { name: "美国", code: "USA" },
    team2: { name: "澳大利亚", code: "AUS" },
    group: "D",
    venue: "西雅图",
    score1: 2,
    score2: 0,
    status: "finished",
  },
  {
    id: 30,
    stage: "group",
    dateUTC: "2026-06-19T22:00:00Z",
    team1: { name: "苏格兰", code: "SCO" },
    team2: { name: "摩洛哥", code: "MAR" },
    group: "C",
    venue: "波士顿",
    score1: 0,
    score2: 1,
    status: "finished",
  },
  {
    id: 31,
    stage: "group",
    dateUTC: "2026-06-20T00:30:00Z",
    team1: { name: "巴西", code: "BRA" },
    team2: { name: "海地", code: "HAI" },
    group: "C",
    venue: "费城",
    score1: 3,
    score2: 0,
    status: "finished",
  },
  {
    id: 32,
    stage: "group",
    dateUTC: "2026-06-20T03:00:00Z",
    team1: { name: "土耳其", code: "TUR" },
    team2: { name: "巴拉圭", code: "PAR" },
    group: "D",
    venue: "旧金山",
    score1: 0,
    score2: 1,
    status: "finished",
  },
  {
    id: 33,
    stage: "group",
    dateUTC: "2026-06-20T17:00:00Z",
    team1: { name: "荷兰", code: "NED" },
    team2: { name: "瑞典", code: "SWE" },
    group: "F",
    venue: "休斯顿",
    score1: 5,
    score2: 1,
    status: "finished",
  },
  {
    id: 34,
    stage: "group",
    dateUTC: "2026-06-20T20:00:00Z",
    team1: { name: "德国", code: "GER" },
    team2: { name: "科特迪瓦", code: "CIV" },
    group: "E",
    venue: "多伦多",
    score1: 2,
    score2: 1,
    status: "finished",
  },
  {
    id: 35,
    stage: "group",
    dateUTC: "2026-06-21T00:00:00Z",
    team1: { name: "厄瓜多尔", code: "ECU" },
    team2: { name: "库拉索", code: "CUW" },
    group: "E",
    venue: "堪萨斯城",
    score1: 0,
    score2: 0,
    status: "finished",
  },
  {
    id: 36,
    stage: "group",
    dateUTC: "2026-06-21T04:00:00Z",
    team1: { name: "突尼斯", code: "TUN" },
    team2: { name: "日本", code: "JPN" },
    group: "F",
    venue: "蒙特雷",
    score1: 0,
    score2: 4,
    status: "finished",
  },
  {
    id: 37,
    stage: "group",
    dateUTC: "2026-06-21T16:00:00Z",
    team1: { name: "西班牙", code: "ESP" },
    team2: { name: "沙特阿拉伯", code: "KSA" },
    group: "H",
    venue: "亚特兰大",
    score1: 4,
    score2: 0,
    status: "finished",
  },
  {
    id: 38,
    stage: "group",
    dateUTC: "2026-06-21T19:00:00Z",
    team1: { name: "比利时", code: "BEL" },
    team2: { name: "伊朗", code: "IRN" },
    group: "G",
    venue: "洛杉矶",
    score1: 0,
    score2: 0,
    status: "finished",
  },
  {
    id: 39,
    stage: "group",
    dateUTC: "2026-06-21T22:00:00Z",
    team1: { name: "乌拉圭", code: "URU" },
    team2: { name: "佛得角", code: "CPV" },
    group: "H",
    venue: "迈阿密",
    score1: 2,
    score2: 2,
    status: "finished",
  },
  {
    id: 40,
    stage: "group",
    dateUTC: "2026-06-22T01:00:00Z",
    team1: { name: "新西兰", code: "NZL" },
    team2: { name: "埃及", code: "EGY" },
    group: "G",
    venue: "温哥华",
    score1: 1,
    score2: 3,
    status: "finished",
  },
  {
    id: 41,
    stage: "group",
    dateUTC: "2026-06-22T17:00:00Z",
    team1: { name: "阿根廷", code: "ARG" },
    team2: { name: "奥地利", code: "AUT" },
    group: "J",
    venue: "达拉斯",
  },
  {
    id: 42,
    stage: "group",
    dateUTC: "2026-06-22T21:00:00Z",
    team1: { name: "法国", code: "FRA" },
    team2: { name: "伊拉克", code: "IRQ" },
    group: "I",
    venue: "费城",
  },
  {
    id: 43,
    stage: "group",
    dateUTC: "2026-06-23T00:00:00Z",
    team1: { name: "挪威", code: "NOR" },
    team2: { name: "塞内加尔", code: "SEN" },
    group: "I",
    venue: "纽约/新泽西",
  },
  {
    id: 44,
    stage: "group",
    dateUTC: "2026-06-23T03:00:00Z",
    team1: { name: "约旦", code: "JOR" },
    team2: { name: "阿尔及利亚", code: "ALG" },
    group: "J",
    venue: "旧金山",
  },
  {
    id: 45,
    stage: "group",
    dateUTC: "2026-06-23T17:00:00Z",
    team1: { name: "葡萄牙", code: "POR" },
    team2: { name: "乌兹别克斯坦", code: "UZB" },
    group: "K",
    venue: "休斯顿",
  },
  {
    id: 46,
    stage: "group",
    dateUTC: "2026-06-23T20:00:00Z",
    team1: { name: "英格兰", code: "ENG" },
    team2: { name: "加纳", code: "GHA" },
    group: "L",
    venue: "波士顿",
  },
  {
    id: 47,
    stage: "group",
    dateUTC: "2026-06-23T23:00:00Z",
    team1: { name: "巴拿马", code: "PAN" },
    team2: { name: "克罗地亚", code: "CRO" },
    group: "L",
    venue: "多伦多",
  },

  // ==================== Group Stage - Matchday 3 ====================
  {
    id: 48,
    stage: "group",
    dateUTC: "2026-06-24T02:00:00Z",
    team1: { name: "哥伦比亚", code: "COL" },
    team2: { name: "刚果(金)", code: "COD" },
    group: "K",
    venue: "瓜达拉哈拉",
  },
  {
    id: 49,
    stage: "group",
    dateUTC: "2026-06-24T19:00:00Z",
    team1: { name: "瑞士", code: "SUI" },
    team2: { name: "加拿大", code: "CAN" },
    group: "B",
    venue: "温哥华",
  },
  {
    id: 50,
    stage: "group",
    dateUTC: "2026-06-24T19:00:00Z",
    team1: { name: "波黑", code: "BIH" },
    team2: { name: "卡塔尔", code: "QAT" },
    group: "B",
    venue: "西雅图",
  },
  {
    id: 51,
    stage: "group",
    dateUTC: "2026-06-24T22:00:00Z",
    team1: { name: "苏格兰", code: "SCO" },
    team2: { name: "巴西", code: "BRA" },
    group: "C",
    venue: "迈阿密",
  },
  {
    id: 52,
    stage: "group",
    dateUTC: "2026-06-24T22:00:00Z",
    team1: { name: "摩洛哥", code: "MAR" },
    team2: { name: "海地", code: "HAI" },
    group: "C",
    venue: "亚特兰大",
  },
  {
    id: 53,
    stage: "group",
    dateUTC: "2026-06-25T01:00:00Z",
    team1: { name: "捷克", code: "CZE" },
    team2: { name: "墨西哥", code: "MEX" },
    group: "A",
    venue: "墨西哥城",
  },
  {
    id: 54,
    stage: "group",
    dateUTC: "2026-06-25T01:00:00Z",
    team1: { name: "南非", code: "RSA" },
    team2: { name: "韩国", code: "KOR" },
    group: "A",
    venue: "蒙特雷",
  },
  {
    id: 55,
    stage: "group",
    dateUTC: "2026-06-25T20:00:00Z",
    team1: { name: "库拉索", code: "CUW" },
    team2: { name: "科特迪瓦", code: "CIV" },
    group: "E",
    venue: "费城",
  },
  {
    id: 56,
    stage: "group",
    dateUTC: "2026-06-25T20:00:00Z",
    team1: { name: "厄瓜多尔", code: "ECU" },
    team2: { name: "德国", code: "GER" },
    group: "E",
    venue: "纽约/新泽西",
  },
  {
    id: 57,
    stage: "group",
    dateUTC: "2026-06-25T23:00:00Z",
    team1: { name: "日本", code: "JPN" },
    team2: { name: "瑞典", code: "SWE" },
    group: "F",
    venue: "达拉斯",
  },
  {
    id: 58,
    stage: "group",
    dateUTC: "2026-06-25T23:00:00Z",
    team1: { name: "突尼斯", code: "TUN" },
    team2: { name: "荷兰", code: "NED" },
    group: "F",
    venue: "堪萨斯城",
  },
  {
    id: 59,
    stage: "group",
    dateUTC: "2026-06-26T02:00:00Z",
    team1: { name: "土耳其", code: "TUR" },
    team2: { name: "美国", code: "USA" },
    group: "D",
    venue: "洛杉矶",
  },
  {
    id: 60,
    stage: "group",
    dateUTC: "2026-06-26T02:00:00Z",
    team1: { name: "巴拉圭", code: "PAR" },
    team2: { name: "澳大利亚", code: "AUS" },
    group: "D",
    venue: "旧金山",
  },
  {
    id: 61,
    stage: "group",
    dateUTC: "2026-06-26T19:00:00Z",
    team1: { name: "挪威", code: "NOR" },
    team2: { name: "法国", code: "FRA" },
    group: "I",
    venue: "波士顿",
  },
  {
    id: 62,
    stage: "group",
    dateUTC: "2026-06-26T19:00:00Z",
    team1: { name: "塞内加尔", code: "SEN" },
    team2: { name: "伊拉克", code: "IRQ" },
    group: "I",
    venue: "多伦多",
  },
  {
    id: 63,
    stage: "group",
    dateUTC: "2026-06-27T00:00:00Z",
    team1: { name: "佛得角", code: "CPV" },
    team2: { name: "沙特阿拉伯", code: "KSA" },
    group: "H",
    venue: "休斯顿",
  },
  {
    id: 64,
    stage: "group",
    dateUTC: "2026-06-27T00:00:00Z",
    team1: { name: "乌拉圭", code: "URU" },
    team2: { name: "西班牙", code: "ESP" },
    group: "H",
    venue: "瓜达拉哈拉",
  },
  {
    id: 65,
    stage: "group",
    dateUTC: "2026-06-27T03:00:00Z",
    team1: { name: "埃及", code: "EGY" },
    team2: { name: "伊朗", code: "IRN" },
    group: "G",
    venue: "西雅图",
  },
  {
    id: 66,
    stage: "group",
    dateUTC: "2026-06-27T03:00:00Z",
    team1: { name: "新西兰", code: "NZL" },
    team2: { name: "比利时", code: "BEL" },
    group: "G",
    venue: "温哥华",
  },
  {
    id: 67,
    stage: "group",
    dateUTC: "2026-06-27T21:00:00Z",
    team1: { name: "巴拿马", code: "PAN" },
    team2: { name: "英格兰", code: "ENG" },
    group: "L",
    venue: "纽约/新泽西",
  },
  {
    id: 68,
    stage: "group",
    dateUTC: "2026-06-27T21:00:00Z",
    team1: { name: "克罗地亚", code: "CRO" },
    team2: { name: "加纳", code: "GHA" },
    group: "L",
    venue: "费城",
  },
  {
    id: 69,
    stage: "group",
    dateUTC: "2026-06-27T23:30:00Z",
    team1: { name: "哥伦比亚", code: "COL" },
    team2: { name: "葡萄牙", code: "POR" },
    group: "K",
    venue: "迈阿密",
  },
  {
    id: 70,
    stage: "group",
    dateUTC: "2026-06-27T23:30:00Z",
    team1: { name: "刚果(金)", code: "COD" },
    team2: { name: "乌兹别克斯坦", code: "UZB" },
    group: "K",
    venue: "亚特兰大",
  },
  {
    id: 71,
    stage: "group",
    dateUTC: "2026-06-28T02:00:00Z",
    team1: { name: "阿尔及利亚", code: "ALG" },
    team2: { name: "奥地利", code: "AUT" },
    group: "J",
    venue: "堪萨斯城",
  },
  {
    id: 72,
    stage: "group",
    dateUTC: "2026-06-28T02:00:00Z",
    team1: { name: "约旦", code: "JOR" },
    team2: { name: "阿根廷", code: "ARG" },
    group: "J",
    venue: "达拉斯",
  },

  // ==================== Round of 32 ====================
  {
    id: 73,
    stage: "round32",
    dateUTC: "2026-06-28T19:00:00Z",
    team1: { name: "2A", code: "TBD", isPlaceholder: true },
    team2: { name: "2B", code: "TBD", isPlaceholder: true },
    venue: "洛杉矶",
  },
  {
    id: 74,
    stage: "round32",
    dateUTC: "2026-06-29T17:00:00Z",
    team1: { name: "1C", code: "TBD", isPlaceholder: true },
    team2: { name: "2F", code: "TBD", isPlaceholder: true },
    venue: "休斯顿",
  },
  {
    id: 75,
    stage: "round32",
    dateUTC: "2026-06-29T20:30:00Z",
    team1: { name: "1E", code: "TBD", isPlaceholder: true },
    team2: { name: "3ABCDF", code: "TBD", isPlaceholder: true },
    venue: "波士顿",
  },
  {
    id: 76,
    stage: "round32",
    dateUTC: "2026-06-30T01:00:00Z",
    team1: { name: "1F", code: "TBD", isPlaceholder: true },
    team2: { name: "2C", code: "TBD", isPlaceholder: true },
    venue: "蒙特雷",
  },
  {
    id: 77,
    stage: "round32",
    dateUTC: "2026-06-30T17:00:00Z",
    team1: { name: "2E", code: "TBD", isPlaceholder: true },
    team2: { name: "2I", code: "TBD", isPlaceholder: true },
    venue: "达拉斯",
  },
  {
    id: 78,
    stage: "round32",
    dateUTC: "2026-06-30T21:00:00Z",
    team1: { name: "1I", code: "TBD", isPlaceholder: true },
    team2: { name: "3CDFGH", code: "TBD", isPlaceholder: true },
    venue: "纽约/新泽西",
  },
  {
    id: 79,
    stage: "round32",
    dateUTC: "2026-07-01T01:00:00Z",
    team1: { name: "1A", code: "TBD", isPlaceholder: true },
    team2: { name: "3CEFHI", code: "TBD", isPlaceholder: true },
    venue: "墨西哥城",
  },
  {
    id: 80,
    stage: "round32",
    dateUTC: "2026-07-01T16:00:00Z",
    team1: { name: "1L", code: "TBD", isPlaceholder: true },
    team2: { name: "3EHIJK", code: "TBD", isPlaceholder: true },
    venue: "亚特兰大",
  },
  {
    id: 81,
    stage: "round32",
    dateUTC: "2026-07-01T20:00:00Z",
    team1: { name: "1G", code: "TBD", isPlaceholder: true },
    team2: { name: "3AEHIJ", code: "TBD", isPlaceholder: true },
    venue: "西雅图",
  },
  {
    id: 82,
    stage: "round32",
    dateUTC: "2026-07-02T00:00:00Z",
    team1: { name: "1D", code: "TBD", isPlaceholder: true },
    team2: { name: "3BEFIJ", code: "TBD", isPlaceholder: true },
    venue: "旧金山",
  },
  {
    id: 83,
    stage: "round32",
    dateUTC: "2026-07-02T19:00:00Z",
    team1: { name: "1H", code: "TBD", isPlaceholder: true },
    team2: { name: "2J", code: "TBD", isPlaceholder: true },
    venue: "洛杉矶",
  },
  {
    id: 84,
    stage: "round32",
    dateUTC: "2026-07-02T23:00:00Z",
    team1: { name: "2K", code: "TBD", isPlaceholder: true },
    team2: { name: "2L", code: "TBD", isPlaceholder: true },
    venue: "多伦多",
  },
  {
    id: 85,
    stage: "round32",
    dateUTC: "2026-07-03T03:00:00Z",
    team1: { name: "1B", code: "TBD", isPlaceholder: true },
    team2: { name: "3EFGIJ", code: "TBD", isPlaceholder: true },
    venue: "温哥华",
  },
  {
    id: 86,
    stage: "round32",
    dateUTC: "2026-07-03T18:00:00Z",
    team1: { name: "2D", code: "TBD", isPlaceholder: true },
    team2: { name: "2G", code: "TBD", isPlaceholder: true },
    venue: "达拉斯",
  },
  {
    id: 87,
    stage: "round32",
    dateUTC: "2026-07-03T22:00:00Z",
    team1: { name: "1J", code: "TBD", isPlaceholder: true },
    team2: { name: "2H", code: "TBD", isPlaceholder: true },
    venue: "迈阿密",
  },
  {
    id: 88,
    stage: "round32",
    dateUTC: "2026-07-04T01:30:00Z",
    team1: { name: "1K", code: "TBD", isPlaceholder: true },
    team2: { name: "3DEIJL", code: "TBD", isPlaceholder: true },
    venue: "堪萨斯城",
  },

  // ==================== Round of 16 ====================
  {
    id: 89,
    stage: "round16",
    dateUTC: "2026-07-04T17:00:00Z",
    team1: { name: "W73", code: "TBD", isPlaceholder: true },
    team2: { name: "W75", code: "TBD", isPlaceholder: true },
    venue: "休斯顿",
  },
  {
    id: 90,
    stage: "round16",
    dateUTC: "2026-07-04T21:00:00Z",
    team1: { name: "W74", code: "TBD", isPlaceholder: true },
    team2: { name: "W77", code: "TBD", isPlaceholder: true },
    venue: "费城",
  },
  {
    id: 91,
    stage: "round16",
    dateUTC: "2026-07-05T20:00:00Z",
    team1: { name: "W76", code: "TBD", isPlaceholder: true },
    team2: { name: "W78", code: "TBD", isPlaceholder: true },
    venue: "纽约/新泽西",
  },
  {
    id: 92,
    stage: "round16",
    dateUTC: "2026-07-06T00:00:00Z",
    team1: { name: "W79", code: "TBD", isPlaceholder: true },
    team2: { name: "W80", code: "TBD", isPlaceholder: true },
    venue: "墨西哥城",
  },
  {
    id: 93,
    stage: "round16",
    dateUTC: "2026-07-06T19:00:00Z",
    team1: { name: "W83", code: "TBD", isPlaceholder: true },
    team2: { name: "W84", code: "TBD", isPlaceholder: true },
    venue: "达拉斯",
  },
  {
    id: 94,
    stage: "round16",
    dateUTC: "2026-07-07T00:00:00Z",
    team1: { name: "W81", code: "TBD", isPlaceholder: true },
    team2: { name: "W82", code: "TBD", isPlaceholder: true },
    venue: "西雅图",
  },
  {
    id: 95,
    stage: "round16",
    dateUTC: "2026-07-07T16:00:00Z",
    team1: { name: "W86", code: "TBD", isPlaceholder: true },
    team2: { name: "W88", code: "TBD", isPlaceholder: true },
    venue: "亚特兰大",
  },
  {
    id: 96,
    stage: "round16",
    dateUTC: "2026-07-07T20:00:00Z",
    team1: { name: "W85", code: "TBD", isPlaceholder: true },
    team2: { name: "W87", code: "TBD", isPlaceholder: true },
    venue: "温哥华",
  },

  // ==================== Quarter-finals ====================
  {
    id: 97,
    stage: "quarterfinal",
    dateUTC: "2026-07-09T20:00:00Z",
    team1: { name: "W89", code: "TBD", isPlaceholder: true },
    team2: { name: "W90", code: "TBD", isPlaceholder: true },
    venue: "波士顿",
  },
  {
    id: 98,
    stage: "quarterfinal",
    dateUTC: "2026-07-10T19:00:00Z",
    team1: { name: "W93", code: "TBD", isPlaceholder: true },
    team2: { name: "W94", code: "TBD", isPlaceholder: true },
    venue: "洛杉矶",
  },
  {
    id: 99,
    stage: "quarterfinal",
    dateUTC: "2026-07-11T21:00:00Z",
    team1: { name: "W91", code: "TBD", isPlaceholder: true },
    team2: { name: "W92", code: "TBD", isPlaceholder: true },
    venue: "迈阿密",
  },
  {
    id: 100,
    stage: "quarterfinal",
    dateUTC: "2026-07-12T01:00:00Z",
    team1: { name: "W95", code: "TBD", isPlaceholder: true },
    team2: { name: "W96", code: "TBD", isPlaceholder: true },
    venue: "堪萨斯城",
  },

  // ==================== Semi-finals ====================
  {
    id: 101,
    stage: "semifinal",
    dateUTC: "2026-07-14T19:00:00Z",
    team1: { name: "W97", code: "TBD", isPlaceholder: true },
    team2: { name: "W98", code: "TBD", isPlaceholder: true },
    venue: "达拉斯",
  },
  {
    id: 102,
    stage: "semifinal",
    dateUTC: "2026-07-15T19:00:00Z",
    team1: { name: "W99", code: "TBD", isPlaceholder: true },
    team2: { name: "W100", code: "TBD", isPlaceholder: true },
    venue: "亚特兰大",
  },

  // ==================== Third Place ====================
  {
    id: 103,
    stage: "thirdplace",
    dateUTC: "2026-07-18T21:00:00Z",
    team1: { name: "RU101", code: "TBD", isPlaceholder: true },
    team2: { name: "RU102", code: "TBD", isPlaceholder: true },
    venue: "迈阿密",
  },

  // ==================== Final ====================
  {
    id: 104,
    stage: "final",
    dateUTC: "2026-07-19T19:00:00Z",
    team1: { name: "W101", code: "TBD", isPlaceholder: true },
    team2: { name: "W102", code: "TBD", isPlaceholder: true },
    venue: "纽约/新泽西",
  },
];

export const stageLabels: Record<string, string> = {
  group: "小组赛",
  round32: "32强赛",
  round16: "16强赛",
  quarterfinal: "四分之一决赛",
  semifinal: "半决赛",
  thirdplace: "季军赛",
  final: "决赛",
};
